# Generated by Django 5.2.14 on 2026-05-08 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_merchants(apps, schema_editor):
    User = apps.get_model("auth", "User")
    MerchantProfile = apps.get_model("accounts", "MerchantProfile")
    for user in User.objects.filter(is_superuser=False):
        MerchantProfile.objects.get_or_create(
            user=user,
            defaults={
                "store_name": user.first_name or user.email or user.username,
                "owner_name": user.first_name,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('business_type', models.CharField(choices=[('grocery', 'Grocery'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('merchant', 'Small merchant'), ('individual', 'Individual seller'), ('other', 'Other')], default='merchant', max_length=24)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended')], default='trial', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['store_name'],
                'indexes': [models.Index(fields=['store_name'], name='accounts_me_store_n_e38737_idx'), models.Index(fields=['subscription_status'], name='accounts_me_subscri_c06e13_idx'), models.Index(fields=['business_type'], name='accounts_me_busines_b6ae9c_idx')],
            },
        ),
        migrations.RunPython(create_profiles_for_existing_merchants, migrations.RunPython.noop),
    ]
