# Generated by Django 5.2.14 on 2026-05-07 21:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def copy_paid_installment_amounts(apps, schema_editor):
    installment = apps.get_model("ledger", "Installment")
    installment.objects.filter(status="paid").update(paid_amount=models.F("amount"))


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunPython(copy_paid_installment_amounts, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DebtActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('payment', 'Payment'), ('charge', 'Charge'), ('note', 'Note')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ledger.debt')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'activity_type', 'created_at'], name='ledger_debt_merchan_4e797c_idx'), models.Index(fields=['debt', 'created_at'], name='ledger_debt_debt_id_69a333_idx')],
            },
        ),
    ]
